const le5leTools = [
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'square',
    label: '正方形',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'rectangle',
    label: '矩形',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'diamond',
    label: '菱形',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'triangle',
    label: '三角形',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'circle',
    label: '圆',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'pentagon',
    label: '五边形',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'hexagon',
    label: '六边形',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'pentagram',
    label: '五角星',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'leftArrow',
    label: '左箭头',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'rightArrow',
    label: '右箭头',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'twowayArrow',
    label: '双向箭头',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'message',
    label: '消息框',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'cloud',
    label: '云',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'file',
    label: '文档',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'image',
    label: '图片',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'text',
    label: '文本',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'cube',
    label: '立方体',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'people',
    label: '用户',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'div',
    label: '视频/网页',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'line',
    label: '分割线',
  },
  {
    subGroup: '基本形状',
    group: '架构拓扑图',
    name: 'lineAlone',
    label: '连线',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'rectangle',
    label: '开始/结束',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'rectangle',
    label: '流程',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'diamond',
    label: '判定',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowData',
    label: '数据',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'hexagon',
    label: '准备',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowSubprocess',
    label: '子流程',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowDb',
    label: '数据库',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowDocument',
    label: '文档',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowInternalStorage',
    label: '内部存储',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowExternStorage',
    label: '外部存储',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowQueue',
    label: '队列',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowManually',
    label: '手动输入',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowDisplay',
    label: '展示',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowParallel',
    label: '并行模式',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'flowComment',
    label: '注释',
  },
  {
    subGroup: '流程图',
    group: 'UML图',
    name: 'people',
    label: '用户',
  },
  {
    subGroup: '活动图',
    group: 'UML图',
    name: 'circle',
    label: '开始',
  },
  {
    subGroup: '活动图',
    group: 'UML图',
    name: 'rectangle',
    label: '活动',
  },
  {
    subGroup: '活动图',
    group: 'UML图',
    name: 'activityFinal',
    label: '结束',
  },
  {
    subGroup: '活动图',
    group: 'UML图',
    name: 'diamond',
    label: '决策/合并',
  },
  {
    subGroup: '活动图',
    group: 'UML图',
    name: 'swimlaneV',
    label: '垂直泳道',
  },
  {
    subGroup: '活动图',
    group: 'UML图',
    name: 'swimlaneH',
    label: '水平泳道',
  },
  {
    subGroup: '活动图',
    group: 'UML图',
    name: 'forkV',
    label: '垂直分岔/汇合',
  },
  {
    subGroup: '活动图',
    group: 'UML图',
    name: 'forkH',
    label: '水平分岔/汇合',
  },
  {
    subGroup: '时序图和类图',
    group: 'UML图',
    name: 'lifeline',
    label: '生命线',
  },
  {
    subGroup: '时序图和类图',
    group: 'UML图',
    name: 'sequenceFocus',
    label: '激活',
  },
  {
    subGroup: '时序图和类图',
    group: 'UML图',
    name: 'simpleClass',
    label: '简单类',
  },
  {
    subGroup: '时序图和类图',
    group: 'UML图',
    name: 'interfaceClass',
    label: '类',
  },
  {
    subGroup: 'Echarts图表',
    group: '图表',
    name: 'echarts',
    label: '折线图',
  },
  {
    subGroup: 'Echarts图表',
    group: '图表',
    name: 'echarts',
    label: '柱状图',
  },
  {
    subGroup: 'Echarts图表',
    group: '图表',
    name: 'echarts',
    label: '饼图',
  },
  {
    subGroup: 'Echarts图表',
    group: '图表',
    name: 'echarts',
    label: '仪表盘',
  },
];
export default {};
