export default {
  pens: [
    {
      id: '07add93',
      type: 0,
      name: 'text',
      rect: {
        x: 422,
        y: 144,
        width: 100,
        height: 30,
        center: {
          x: 472,
          y: 159,
        },
        ex: 522,
        ey: 174,
      },
      lineWidth: 1,
      rotate: 0,
      offsetRotate: 0,
      globalAlpha: 1,
      dash: 0,
      strokeStyle: '#222',
      fillStyle: '',
      font: {
        color: '#222',
        fontFamily:
          '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
        fontSize: 12,
        lineHeight: 1.5,
        fontStyle: 'normal',
        fontWeight: 'normal',
        textAlign: 'center',
        textBaseline: 'middle',
      },
      animateCycleIndex: 0,
      events: [],
      eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
      tags: [],
      lineDashOffset: 0,
      text: '文字',
      textOffsetX: 0,
      textOffsetY: 0,
      animateType: '',
      visible: true,
      data: '',
      zRotate: 0,
      anchors: [
        {
          x: 422,
          y: 159,
          direction: 4,
        },
        {
          x: 472,
          y: 144,
          direction: 1,
        },
        {
          x: 522,
          y: 159,
          direction: 2,
        },
        {
          x: 472,
          y: 174,
          direction: 3,
        },
      ],
      rotatedAnchors: [
        {
          x: 422,
          y: 159,
          direction: 4,
        },
        {
          x: 472,
          y: 144,
          direction: 1,
        },
        {
          x: 522,
          y: 159,
          direction: 2,
        },
        {
          x: 472,
          y: 174,
          direction: 3,
        },
      ],
      animateDuration: 0,
      animateFrames: [],
      borderRadius: 0,
      iconSize: null,
      imageAlign: 'center',
      bkType: 0,
      gradientAngle: 0,
      gradientRadius: 0.01,
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingLeftNum: 0,
      paddingRightNum: 0,
      paddingTopNum: 0,
      paddingBottomNum: 0,
      textRect: {
        x: 422,
        y: 166.5,
        width: 100,
        height: 7.5,
        center: {
          x: 472,
          y: 170.25,
        },
        ex: 522,
        ey: 174,
      },
      fullTextRect: {
        x: 422,
        y: 144,
        width: 100,
        height: 30,
        center: {
          x: 472,
          y: 159,
        },
        ex: 522,
        ey: 174,
      },
      iconRect: {
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        center: {
          x: 0,
          y: 0,
        },
        ex: 0,
        ey: 0,
      },
      elementRendered: false,
      TID: '14f4dd06',
    },
    {
      id: '57877390',
      type: 0,
      name: 'file',
      rect: {
        x: 256,
        y: 210,
        width: 80,
        height: 100,
        center: {
          x: 296,
          y: 260,
        },
        ex: 336,
        ey: 310,
      },
      lineWidth: 1,
      rotate: 0,
      offsetRotate: 0,
      globalAlpha: 1,
      dash: 2,
      strokeStyle: '#fa8c16',
      fillStyle: '#cf2929ff',
      font: {
        color: '#222',
        fontFamily:
          '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
        fontSize: 12,
        lineHeight: 1.5,
        fontStyle: 'normal',
        fontWeight: 'normal',
        textAlign: 'center',
        textBaseline: 'middle',
      },
      animateCycleIndex: 358,
      events: [],
      eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
      tags: [],
      lineDashOffset: 0,
      text: '文档',
      textOffsetX: 0,
      textOffsetY: 0,
      animateType: 'custom',
      visible: true,
      data: '',
      zRotate: 0,
      anchors: [
        {
          x: 256,
          y: 260,
          direction: 4,
        },
        {
          x: 296,
          y: 210,
          direction: 1,
        },
        {
          x: 336,
          y: 260,
          direction: 2,
        },
        {
          x: 296,
          y: 310,
          direction: 3,
        },
      ],
      rotatedAnchors: [
        {
          x: 256,
          y: 260,
          direction: 4,
        },
        {
          x: 296,
          y: 210,
          direction: 1,
        },
        {
          x: 336,
          y: 260,
          direction: 2,
        },
        {
          x: 296,
          y: 310,
          direction: 3,
        },
      ],
      animateDuration: 1100,
      animateFrames: [
        {
          duration: 300,
          linear: true,
          state: {
            id: '57877390',
            type: 0,
            name: 'file',
            rect: {
              x: 256,
              y: 210,
              width: 80,
              height: 100,
              center: {
                x: 296,
                y: 260,
              },
              ex: 336,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 2,
            strokeStyle: '#fa8c16',
            fillStyle: '#cf2929ff',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '文档',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'warning',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 0,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 266,
              y: 280,
              width: 60,
              height: 20,
              center: {
                x: 296,
                y: 290,
              },
              ex: 326,
              ey: 300,
            },
            fullTextRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            iconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 55,
              center: {
                x: 296,
                y: 247.5,
              },
              ex: 326,
              ey: 275,
            },
            fullIconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            elementRendered: false,
          },
          start: 0,
          end: 300,
          initState: {
            id: '57877390',
            type: 0,
            name: 'file',
            rect: {
              x: 256,
              y: 210,
              width: 80,
              height: 100,
              center: {
                x: 296,
                y: 260,
              },
              ex: 336,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#fa8c16',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '文档',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'custom',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 1100,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 266,
              y: 280,
              width: 60,
              height: 20,
              center: {
                x: 296,
                y: 290,
              },
              ex: 326,
              ey: 300,
            },
            fullTextRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            iconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 55,
              center: {
                x: 296,
                y: 247.5,
              },
              ex: 326,
              ey: 275,
            },
            fullIconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            elementRendered: false,
          },
        },
        {
          duration: 500,
          linear: true,
          state: {
            id: '57877390',
            type: 0,
            name: 'file',
            rect: {
              x: 256,
              y: 210,
              width: 80,
              height: 100,
              center: {
                x: 296,
                y: 260,
              },
              ex: 336,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#fa8c16',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '文档',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'warning',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 0,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 266,
              y: 280,
              width: 60,
              height: 20,
              center: {
                x: 296,
                y: 290,
              },
              ex: 326,
              ey: 300,
            },
            fullTextRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            iconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 55,
              center: {
                x: 296,
                y: 247.5,
              },
              ex: 326,
              ey: 275,
            },
            fullIconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            elementRendered: false,
          },
          start: 300,
          end: 800,
          initState: {
            id: '57877390',
            type: 0,
            name: 'file',
            rect: {
              x: 256,
              y: 210,
              width: 80,
              height: 100,
              center: {
                x: 296,
                y: 260,
              },
              ex: 336,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 2,
            strokeStyle: '#fa8c16',
            fillStyle: '#cf2929ff',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '文档',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'warning',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 0,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 266,
              y: 280,
              width: 60,
              height: 20,
              center: {
                x: 296,
                y: 290,
              },
              ex: 326,
              ey: 300,
            },
            fullTextRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            iconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 55,
              center: {
                x: 296,
                y: 247.5,
              },
              ex: 326,
              ey: 275,
            },
            fullIconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            elementRendered: false,
          },
        },
        {
          duration: 300,
          linear: true,
          state: {
            id: '57877390',
            type: 0,
            name: 'file',
            rect: {
              x: 256,
              y: 210,
              width: 80,
              height: 100,
              center: {
                x: 296,
                y: 260,
              },
              ex: 336,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 2,
            strokeStyle: '#fa8c16',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '文档',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'warning',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 0,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 266,
              y: 280,
              width: 60,
              height: 20,
              center: {
                x: 296,
                y: 290,
              },
              ex: 326,
              ey: 300,
            },
            fullTextRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            iconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 55,
              center: {
                x: 296,
                y: 247.5,
              },
              ex: 326,
              ey: 275,
            },
            fullIconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            elementRendered: false,
          },
          start: 800,
          end: 1100,
          initState: {
            id: '57877390',
            type: 0,
            name: 'file',
            rect: {
              x: 256,
              y: 210,
              width: 80,
              height: 100,
              center: {
                x: 296,
                y: 260,
              },
              ex: 336,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#fa8c16',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '文档',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'warning',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 256,
                y: 260,
                direction: 4,
              },
              {
                x: 296,
                y: 210,
                direction: 1,
              },
              {
                x: 336,
                y: 260,
                direction: 2,
              },
              {
                x: 296,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 0,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 266,
              y: 280,
              width: 60,
              height: 20,
              center: {
                x: 296,
                y: 290,
              },
              ex: 326,
              ey: 300,
            },
            fullTextRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            iconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 55,
              center: {
                x: 296,
                y: 247.5,
              },
              ex: 326,
              ey: 275,
            },
            fullIconRect: {
              x: 266,
              y: 220,
              width: 60,
              height: 80,
              center: {
                x: 296,
                y: 260,
              },
              ex: 326,
              ey: 300,
            },
            elementRendered: false,
          },
        },
      ],
      borderRadius: 0,
      iconSize: null,
      imageAlign: 'center',
      bkType: 0,
      gradientAngle: 0,
      gradientRadius: 0.01,
      paddingTop: 10,
      paddingBottom: 10,
      paddingLeft: 10,
      paddingRight: 10,
      paddingLeftNum: 10,
      paddingRightNum: 10,
      paddingTopNum: 10,
      paddingBottomNum: 10,
      textRect: {
        x: 266,
        y: 280,
        width: 60,
        height: 20,
        center: {
          x: 296,
          y: 290,
        },
        ex: 326,
        ey: 300,
      },
      fullTextRect: {
        x: 266,
        y: 220,
        width: 60,
        height: 80,
        center: {
          x: 296,
          y: 260,
        },
        ex: 326,
        ey: 300,
      },
      iconRect: {
        x: 266,
        y: 220,
        width: 60,
        height: 55,
        center: {
          x: 296,
          y: 247.5,
        },
        ex: 326,
        ey: 275,
      },
      fullIconRect: {
        x: 266,
        y: 220,
        width: 60,
        height: 80,
        center: {
          x: 296,
          y: 260,
        },
        ex: 326,
        ey: 300,
      },
      elementRendered: false,
      TID: '14f4dd06',
      dockWatchers: [
        {
          x: 296,
          y: 260,
        },
        {
          x: 256,
          y: 210,
        },
        {
          x: 336,
          y: 210,
        },
        {
          x: 336,
          y: 310,
        },
        {
          x: 256,
          y: 310,
        },
      ],
      animateStart: 1594263171145,
    },
    {
      id: '798193f',
      type: 0,
      name: 'image',
      rect: {
        x: 60,
        y: 151,
        width: 100,
        height: 100,
        center: {
          x: 110,
          y: 201,
        },
        ex: 160,
        ey: 251,
      },
      lineWidth: 1,
      rotate: 0,
      offsetRotate: 0,
      globalAlpha: 1,
      dash: 0,
      strokeStyle: '#222',
      fillStyle: '',
      font: {
        color: '#222',
        fontFamily:
          '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
        fontSize: 12,
        lineHeight: 1.5,
        fontStyle: 'normal',
        fontWeight: 'normal',
        textAlign: 'center',
        textBaseline: 'middle',
      },
      animateCycleIndex: 0,
      events: [],
      eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
      tags: [],
      lineDashOffset: 0,
      textOffsetX: 0,
      textOffsetY: 0,
      animateType: '',
      visible: true,
      data: '',
      zRotate: 0,
      anchors: [
        {
          x: 60,
          y: 201,
          direction: 4,
        },
        {
          x: 110,
          y: 151,
          direction: 1,
        },
        {
          x: 160,
          y: 201,
          direction: 2,
        },
        {
          x: 110,
          y: 251,
          direction: 3,
        },
      ],
      rotatedAnchors: [
        {
          x: 60,
          y: 201,
          direction: 4,
        },
        {
          x: 110,
          y: 151,
          direction: 1,
        },
        {
          x: 160,
          y: 201,
          direction: 2,
        },
        {
          x: 110,
          y: 251,
          direction: 3,
        },
      ],
      animateDuration: 0,
      animateFrames: [],
      borderRadius: 0,
      iconSize: null,
      image: '/assets/img/logo.png',
      imageAlign: 'center',
      bkType: 0,
      gradientAngle: 0,
      gradientRadius: 0.01,
      paddingTop: 10,
      paddingBottom: 10,
      paddingLeft: 10,
      paddingRight: 10,
      paddingLeftNum: 10,
      paddingRightNum: 10,
      paddingTopNum: 10,
      paddingBottomNum: 10,
      textRect: {
        x: 60,
        y: 233,
        width: 100,
        height: 18,
        center: {
          x: 110,
          y: 242,
        },
        ex: 160,
        ey: 251,
      },
      fullTextRect: {
        x: 60,
        y: 151,
        width: 100,
        height: 100,
        center: {
          x: 110,
          y: 201,
        },
        ex: 160,
        ey: 251,
      },
      iconRect: {
        x: 60,
        y: 151,
        width: 100,
        height: 77,
        center: {
          x: 110,
          y: 189.5,
        },
        ex: 160,
        ey: 228,
      },
      fullIconRect: {
        x: 60,
        y: 151,
        width: 100,
        height: 100,
        center: {
          x: 110,
          y: 201,
        },
        ex: 160,
        ey: 251,
      },
      elementRendered: false,
      TID: '14f4dd06',
      img: {
        __zone_symbol__loadfalse: [
          {
            type: 'eventTask',
            state: 'scheduled',
            source: 'HTMLImageElement.addEventListener:load',
            zone: 'angular',
            runCount: 2,
          },
        ],
      },
      lastImage: '/assets/img/logo.png',
      imgNaturalWidth: 200,
      imgNaturalHeight: 200,
      dockWatchers: [
        {
          x: 110,
          y: 201,
        },
        {
          x: 60,
          y: 151,
        },
        {
          x: 160,
          y: 151,
        },
        {
          x: 160,
          y: 251,
        },
        {
          x: 60,
          y: 251,
        },
      ],
    },
    {
      id: '32533803',
      type: 0,
      name: 'rectangle',
      rect: {
        x: 508,
        y: 270,
        width: 120,
        height: 40,
        center: {
          x: 568,
          y: 290,
        },
        ex: 628,
        ey: 310,
      },
      lineWidth: 1,
      rotate: 0,
      offsetRotate: 0,
      globalAlpha: 1,
      dash: 0,
      strokeStyle: '#222',
      fillStyle: '#3ee551ff',
      font: {
        color: '#222',
        fontFamily:
          '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
        fontSize: 12,
        lineHeight: 1.5,
        fontStyle: 'normal',
        fontWeight: 'normal',
        textAlign: 'center',
        textBaseline: 'middle',
      },
      animateCycleIndex: 704,
      events: [],
      eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
      tags: [],
      lineDashOffset: 0,
      text: '流程',
      textOffsetX: 0,
      textOffsetY: 0,
      animateType: 'custom',
      visible: true,
      data: '',
      zRotate: 0,
      anchors: [
        {
          x: 508,
          y: 290,
          direction: 4,
        },
        {
          x: 568,
          y: 270,
          direction: 1,
        },
        {
          x: 628,
          y: 290,
          direction: 2,
        },
        {
          x: 568,
          y: 310,
          direction: 3,
        },
      ],
      rotatedAnchors: [
        {
          x: 508,
          y: 290,
          direction: 4,
        },
        {
          x: 568,
          y: 270,
          direction: 1,
        },
        {
          x: 628,
          y: 290,
          direction: 2,
        },
        {
          x: 568,
          y: 310,
          direction: 3,
        },
      ],
      animateDuration: 400,
      animateFrames: [
        {
          duration: 200,
          linear: true,
          state: {
            id: '32533803',
            type: 0,
            name: 'rectangle',
            rect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#222',
            fillStyle: '#3ee551ff',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '流程',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'custom',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 508,
                y: 290,
                direction: 4,
              },
              {
                x: 568,
                y: 270,
                direction: 1,
              },
              {
                x: 628,
                y: 290,
                direction: 2,
              },
              {
                x: 568,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 508,
                y: 290,
                direction: 4,
              },
              {
                x: 568,
                y: 270,
                direction: 1,
              },
              {
                x: 628,
                y: 290,
                direction: 2,
              },
              {
                x: 568,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 0,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 0,
            paddingBottom: 0,
            paddingLeft: 0,
            paddingRight: 0,
            paddingLeftNum: 0,
            paddingRightNum: 0,
            paddingTopNum: 0,
            paddingBottomNum: 0,
            textRect: {
              x: 548,
              y: 270,
              width: 80,
              height: 40,
              center: {
                x: 588,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            fullTextRect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            iconRect: {
              x: 508,
              y: 270,
              width: 40,
              height: 40,
              center: {
                x: 528,
                y: 290,
              },
              ex: 548,
              ey: 310,
            },
            fullIconRect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            elementRendered: false,
          },
          start: 0,
          end: 200,
          initState: {
            id: '32533803',
            type: 0,
            name: 'rectangle',
            rect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#222',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '流程',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'custom',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 508,
                y: 290,
                direction: 4,
              },
              {
                x: 568,
                y: 270,
                direction: 1,
              },
              {
                x: 628,
                y: 290,
                direction: 2,
              },
              {
                x: 568,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 508,
                y: 290,
                direction: 4,
              },
              {
                x: 568,
                y: 270,
                direction: 1,
              },
              {
                x: 628,
                y: 290,
                direction: 2,
              },
              {
                x: 568,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 400,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 0,
            paddingBottom: 0,
            paddingLeft: 0,
            paddingRight: 0,
            paddingLeftNum: 0,
            paddingRightNum: 0,
            paddingTopNum: 0,
            paddingBottomNum: 0,
            textRect: {
              x: 548,
              y: 270,
              width: 80,
              height: 40,
              center: {
                x: 588,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            fullTextRect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            iconRect: {
              x: 508,
              y: 270,
              width: 40,
              height: 40,
              center: {
                x: 528,
                y: 290,
              },
              ex: 548,
              ey: 310,
            },
            fullIconRect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            elementRendered: false,
          },
        },
        {
          duration: 200,
          linear: true,
          state: {
            id: '32533803',
            type: 0,
            name: 'rectangle',
            rect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#222',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '流程',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'custom',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 508,
                y: 290,
                direction: 4,
              },
              {
                x: 568,
                y: 270,
                direction: 1,
              },
              {
                x: 628,
                y: 290,
                direction: 2,
              },
              {
                x: 568,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 508,
                y: 290,
                direction: 4,
              },
              {
                x: 568,
                y: 270,
                direction: 1,
              },
              {
                x: 628,
                y: 290,
                direction: 2,
              },
              {
                x: 568,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 200,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 0,
            paddingBottom: 0,
            paddingLeft: 0,
            paddingRight: 0,
            paddingLeftNum: 0,
            paddingRightNum: 0,
            paddingTopNum: 0,
            paddingBottomNum: 0,
            textRect: {
              x: 548,
              y: 270,
              width: 80,
              height: 40,
              center: {
                x: 588,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            fullTextRect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            iconRect: {
              x: 508,
              y: 270,
              width: 40,
              height: 40,
              center: {
                x: 528,
                y: 290,
              },
              ex: 548,
              ey: 310,
            },
            fullIconRect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            elementRendered: false,
          },
          start: 200,
          end: 400,
          initState: {
            id: '32533803',
            type: 0,
            name: 'rectangle',
            rect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#222',
            fillStyle: '#3ee551ff',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            text: '流程',
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'custom',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 508,
                y: 290,
                direction: 4,
              },
              {
                x: 568,
                y: 270,
                direction: 1,
              },
              {
                x: 628,
                y: 290,
                direction: 2,
              },
              {
                x: 568,
                y: 310,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 508,
                y: 290,
                direction: 4,
              },
              {
                x: 568,
                y: 270,
                direction: 1,
              },
              {
                x: 628,
                y: 290,
                direction: 2,
              },
              {
                x: 568,
                y: 310,
                direction: 3,
              },
            ],
            animateDuration: 0,
            borderRadius: 0,
            iconSize: null,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 0,
            paddingBottom: 0,
            paddingLeft: 0,
            paddingRight: 0,
            paddingLeftNum: 0,
            paddingRightNum: 0,
            paddingTopNum: 0,
            paddingBottomNum: 0,
            textRect: {
              x: 548,
              y: 270,
              width: 80,
              height: 40,
              center: {
                x: 588,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            fullTextRect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            iconRect: {
              x: 508,
              y: 270,
              width: 40,
              height: 40,
              center: {
                x: 528,
                y: 290,
              },
              ex: 548,
              ey: 310,
            },
            fullIconRect: {
              x: 508,
              y: 270,
              width: 120,
              height: 40,
              center: {
                x: 568,
                y: 290,
              },
              ex: 628,
              ey: 310,
            },
            elementRendered: false,
          },
        },
      ],
      borderRadius: 0,
      iconSize: null,
      imageAlign: 'center',
      bkType: 0,
      gradientAngle: 0,
      gradientRadius: 0.01,
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingLeftNum: 0,
      paddingRightNum: 0,
      paddingTopNum: 0,
      paddingBottomNum: 0,
      textRect: {
        x: 548,
        y: 270,
        width: 80,
        height: 40,
        center: {
          x: 588,
          y: 290,
        },
        ex: 628,
        ey: 310,
      },
      fullTextRect: {
        x: 508,
        y: 270,
        width: 120,
        height: 40,
        center: {
          x: 568,
          y: 290,
        },
        ex: 628,
        ey: 310,
      },
      iconRect: {
        x: 508,
        y: 270,
        width: 40,
        height: 40,
        center: {
          x: 528,
          y: 290,
        },
        ex: 548,
        ey: 310,
      },
      fullIconRect: {
        x: 508,
        y: 270,
        width: 120,
        height: 40,
        center: {
          x: 568,
          y: 290,
        },
        ex: 628,
        ey: 310,
      },
      elementRendered: false,
      TID: '14f4dd06',
      dockWatchers: [
        {
          x: 568,
          y: 290,
        },
        {
          x: 508,
          y: 270,
        },
        {
          x: 628,
          y: 270,
        },
        {
          x: 628,
          y: 310,
        },
        {
          x: 508,
          y: 310,
        },
      ],
      animateStart: 1594263171145,
    },
    {
      id: '1912c89e',
      type: 0,
      name: 'hexagon',
      rect: {
        x: 236,
        y: 390,
        width: 120,
        height: 50,
        center: {
          x: 296,
          y: 415,
        },
        ex: 356,
        ey: 440,
      },
      lineWidth: 1,
      rotate: 0,
      offsetRotate: 0,
      globalAlpha: 1,
      dash: 0,
      strokeStyle: '#222',
      fillStyle: '',
      font: {
        color: '#222',
        fontFamily:
          '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
        fontSize: 12,
        lineHeight: 1.5,
        fontStyle: 'normal',
        fontWeight: 'normal',
        textAlign: 'center',
        textBaseline: 'middle',
      },
      animateCycleIndex: 0,
      events: [],
      eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
      tags: [],
      lineDashOffset: 0,
      text: '准备',
      textOffsetX: 0,
      textOffsetY: 0,
      animateType: '',
      visible: true,
      data: '',
      zRotate: 0,
      anchors: [
        {
          x: 296,
          y: 390,
          direction: 1,
        },
        {
          x: 356,
          y: 415,
          direction: 2,
        },
        {
          x: 296,
          y: 440,
          direction: 3,
        },
        {
          x: 236,
          y: 415,
          direction: 4,
        },
        {
          x: 248,
          y: 402.5,
          direction: 4,
          hidden: true,
        },
        {
          x: 248,
          y: 427.5,
          direction: 4,
          hidden: true,
        },
        {
          x: 344,
          y: 402.5,
          direction: 2,
          hidden: true,
        },
        {
          x: 344,
          y: 427.5,
          direction: 2,
          hidden: true,
        },
      ],
      rotatedAnchors: [
        {
          x: 296,
          y: 390,
          direction: 1,
        },
        {
          x: 356,
          y: 415,
          direction: 2,
        },
        {
          x: 296,
          y: 440,
          direction: 3,
        },
        {
          x: 236,
          y: 415,
          direction: 4,
        },
        {
          x: 248,
          y: 402.5,
          direction: 4,
          hidden: true,
        },
        {
          x: 248,
          y: 427.5,
          direction: 4,
          hidden: true,
        },
        {
          x: 344,
          y: 402.5,
          direction: 2,
          hidden: true,
        },
        {
          x: 344,
          y: 427.5,
          direction: 2,
          hidden: true,
        },
      ],
      animateDuration: 0,
      animateFrames: [],
      borderRadius: 0,
      iconSize: null,
      imageAlign: 'center',
      bkType: 0,
      gradientAngle: 0,
      gradientRadius: 0.01,
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingLeftNum: 0,
      paddingRightNum: 0,
      paddingTopNum: 0,
      paddingBottomNum: 0,
      textRect: {
        x: 260,
        y: 427.5,
        width: 72,
        height: 12.5,
        center: {
          x: 296,
          y: 433.75,
        },
        ex: 332,
        ey: 440,
      },
      fullTextRect: {
        x: 260,
        y: 390,
        width: 72,
        height: 50,
        center: {
          x: 296,
          y: 415,
        },
        ex: 332,
        ey: 440,
      },
      iconRect: {
        x: 260,
        y: 390,
        width: 72,
        height: 37.5,
        center: {
          x: 296,
          y: 408.75,
        },
        ex: 332,
        ey: 427.5,
      },
      fullIconRect: {
        x: 260,
        y: 390,
        width: 72,
        height: 50,
        center: {
          x: 296,
          y: 415,
        },
        ex: 332,
        ey: 440,
      },
      elementRendered: false,
      TID: '14f4dd06',
      dockWatchers: [
        {
          x: 296,
          y: 415,
        },
        {
          x: 236,
          y: 390,
        },
        {
          x: 356,
          y: 390,
        },
        {
          x: 356,
          y: 440,
        },
        {
          x: 236,
          y: 440,
        },
      ],
    },
    {
      id: 'd12de73',
      type: 0,
      name: 'image',
      rect: {
        x: 835,
        y: 101,
        width: 100,
        height: 100,
        center: {
          x: 885,
          y: 151,
        },
        ex: 935,
        ey: 201,
      },
      lineWidth: 1,
      rotate: 239.14042245,
      offsetRotate: 0,
      globalAlpha: 1,
      dash: 0,
      strokeStyle: '#222',
      fillStyle: '',
      font: {
        color: '#222',
        fontFamily:
          '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
        fontSize: 12,
        lineHeight: 1.5,
        fontStyle: 'normal',
        fontWeight: 'normal',
        textAlign: 'center',
        textBaseline: 'middle',
      },
      animateCycleIndex: 108,
      events: [],
      eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
      tags: [],
      lineDashOffset: 0,
      textOffsetX: 0,
      textOffsetY: 0,
      animateType: 'custom',
      visible: true,
      data: '',
      zRotate: 0,
      anchors: [
        {
          x: 835,
          y: 151,
          direction: 4,
        },
        {
          x: 885,
          y: 101,
          direction: 1,
        },
        {
          x: 935,
          y: 151,
          direction: 2,
        },
        {
          x: 885,
          y: 201,
          direction: 3,
        },
      ],
      rotatedAnchors: [
        {
          x: 910.6467877678243,
          y: 193.92134989946354,
          direction: 4,
        },
        {
          x: 842.0786501005365,
          y: 176.6467877678243,
          direction: 1,
        },
        {
          x: 859.3532122321757,
          y: 108.07865010053646,
          direction: 2,
        },
        {
          x: 927.9213498994635,
          y: 125.35321223217571,
          direction: 3,
        },
      ],
      animateDuration: 2000,
      animateFrames: [
        {
          duration: 2000,
          linear: true,
          state: {
            id: 'd12de73',
            type: 0,
            name: 'image',
            rect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            lineWidth: 1,
            rotate: 360,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#222',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'custom',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 835,
                y: 151,
                direction: 4,
              },
              {
                x: 885,
                y: 101,
                direction: 1,
              },
              {
                x: 935,
                y: 151,
                direction: 2,
              },
              {
                x: 885,
                y: 201,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 835,
                y: 151,
                direction: 4,
              },
              {
                x: 885,
                y: 101,
                direction: 1,
              },
              {
                x: 935,
                y: 151,
                direction: 2,
              },
              {
                x: 885,
                y: 201,
                direction: 3,
              },
            ],
            animateDuration: 0,
            borderRadius: 0,
            iconSize: null,
            image: '/assets/img/logo.png',
            imgNaturalWidth: 200,
            imgNaturalHeight: 200,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 835,
              y: 183,
              width: 100,
              height: 18,
              center: {
                x: 885,
                y: 192,
              },
              ex: 935,
              ey: 201,
            },
            fullTextRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            iconRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 77,
              center: {
                x: 885,
                y: 139.5,
              },
              ex: 935,
              ey: 178,
            },
            fullIconRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            elementRendered: false,
          },
          start: 0,
          end: 2000,
          initState: {
            id: 'd12de73',
            type: 0,
            name: 'image',
            rect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            lineWidth: 1,
            rotate: 140.45489999999998,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#222',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'custom',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 835,
                y: 151,
                direction: 4,
              },
              {
                x: 885,
                y: 101,
                direction: 1,
              },
              {
                x: 935,
                y: 151,
                direction: 2,
              },
              {
                x: 885,
                y: 201,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 923.5561829780104,
                y: 119.16572987853843,
                direction: 4,
              },
              {
                x: 916.8342701214616,
                y: 189.5561829780104,
                direction: 1,
              },
              {
                x: 846.4438170219896,
                y: 182.83427012146157,
                direction: 2,
              },
              {
                x: 853.1657298785384,
                y: 112.44381702198959,
                direction: 3,
              },
            ],
            animateDuration: 2000,
            borderRadius: 0,
            iconSize: null,
            image: '/assets/img/logo.png',
            imgNaturalWidth: 200,
            imgNaturalHeight: 200,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 835,
              y: 183,
              width: 100,
              height: 18,
              center: {
                x: 885,
                y: 192,
              },
              ex: 935,
              ey: 201,
            },
            fullTextRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            iconRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 77,
              center: {
                x: 885,
                y: 139.5,
              },
              ex: 935,
              ey: 178,
            },
            fullIconRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            elementRendered: false,
          },
        },
        {
          duration: 0,
          linear: true,
          state: {
            id: 'd12de73',
            type: 0,
            name: 'image',
            rect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            lineWidth: 1,
            rotate: 0,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#222',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'custom',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 835,
                y: 151,
                direction: 4,
              },
              {
                x: 885,
                y: 101,
                direction: 1,
              },
              {
                x: 935,
                y: 151,
                direction: 2,
              },
              {
                x: 885,
                y: 201,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 835,
                y: 151,
                direction: 4,
              },
              {
                x: 885,
                y: 101,
                direction: 1,
              },
              {
                x: 935,
                y: 151,
                direction: 2,
              },
              {
                x: 885,
                y: 201,
                direction: 3,
              },
            ],
            animateDuration: 200,
            borderRadius: 0,
            iconSize: null,
            image: '/assets/img/logo.png',
            imgNaturalWidth: 200,
            imgNaturalHeight: 200,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 835,
              y: 183,
              width: 100,
              height: 18,
              center: {
                x: 885,
                y: 192,
              },
              ex: 935,
              ey: 201,
            },
            fullTextRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            iconRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 77,
              center: {
                x: 885,
                y: 139.5,
              },
              ex: 935,
              ey: 178,
            },
            fullIconRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            elementRendered: false,
          },
          start: 2000,
          end: 2000,
          initState: {
            id: 'd12de73',
            type: 0,
            name: 'image',
            rect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            lineWidth: 1,
            rotate: 360,
            offsetRotate: 0,
            globalAlpha: 1,
            dash: 0,
            strokeStyle: '#222',
            fillStyle: '',
            font: {
              color: '#222',
              fontFamily:
                '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
              fontSize: 12,
              lineHeight: 1.5,
              fontStyle: 'normal',
              fontWeight: 'normal',
              textAlign: 'center',
              textBaseline: 'middle',
            },
            animateCycleIndex: 0,
            events: [],
            eventFns: ['link', 'doAnimate', 'doFn', 'doWindowFn'],
            tags: [],
            lineDashOffset: 0,
            textOffsetX: 0,
            textOffsetY: 0,
            animateType: 'custom',
            visible: true,
            data: '',
            zRotate: 0,
            anchors: [
              {
                x: 835,
                y: 151,
                direction: 4,
              },
              {
                x: 885,
                y: 101,
                direction: 1,
              },
              {
                x: 935,
                y: 151,
                direction: 2,
              },
              {
                x: 885,
                y: 201,
                direction: 3,
              },
            ],
            rotatedAnchors: [
              {
                x: 835,
                y: 151,
                direction: 4,
              },
              {
                x: 885,
                y: 101,
                direction: 1,
              },
              {
                x: 935,
                y: 151,
                direction: 2,
              },
              {
                x: 885,
                y: 201,
                direction: 3,
              },
            ],
            animateDuration: 0,
            borderRadius: 0,
            iconSize: null,
            image: '/assets/img/logo.png',
            imgNaturalWidth: 200,
            imgNaturalHeight: 200,
            imageAlign: 'center',
            bkType: 0,
            gradientAngle: 0,
            gradientRadius: 0.01,
            paddingTop: 10,
            paddingBottom: 10,
            paddingLeft: 10,
            paddingRight: 10,
            paddingLeftNum: 10,
            paddingRightNum: 10,
            paddingTopNum: 10,
            paddingBottomNum: 10,
            textRect: {
              x: 835,
              y: 183,
              width: 100,
              height: 18,
              center: {
                x: 885,
                y: 192,
              },
              ex: 935,
              ey: 201,
            },
            fullTextRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            iconRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 77,
              center: {
                x: 885,
                y: 139.5,
              },
              ex: 935,
              ey: 178,
            },
            fullIconRect: {
              x: 835,
              y: 101,
              width: 100,
              height: 100,
              center: {
                x: 885,
                y: 151,
              },
              ex: 935,
              ey: 201,
            },
            elementRendered: false,
          },
        },
      ],
      borderRadius: 0,
      iconSize: null,
      image: '/assets/img/logo.png',
      imageAlign: 'center',
      bkType: 0,
      gradientAngle: 0,
      gradientRadius: 0.01,
      paddingTop: 10,
      paddingBottom: 10,
      paddingLeft: 10,
      paddingRight: 10,
      paddingLeftNum: 10,
      paddingRightNum: 10,
      paddingTopNum: 10,
      paddingBottomNum: 10,
      textRect: {
        x: 835,
        y: 183,
        width: 100,
        height: 18,
        center: {
          x: 885,
          y: 192,
        },
        ex: 935,
        ey: 201,
      },
      fullTextRect: {
        x: 835,
        y: 101,
        width: 100,
        height: 100,
        center: {
          x: 885,
          y: 151,
        },
        ex: 935,
        ey: 201,
      },
      iconRect: {
        x: 835,
        y: 101,
        width: 100,
        height: 77,
        center: {
          x: 885,
          y: 139.5,
        },
        ex: 935,
        ey: 178,
      },
      fullIconRect: {
        x: 835,
        y: 101,
        width: 100,
        height: 100,
        center: {
          x: 885,
          y: 151,
        },
        ex: 935,
        ey: 201,
      },
      elementRendered: false,
      TID: '14f4dd06',
      img: {
        __zone_symbol__loadfalse: [
          {
            type: 'eventTask',
            state: 'scheduled',
            source: 'HTMLImageElement.addEventListener:load',
            zone: 'angular',
            runCount: 2,
          },
        ],
      },
      lastImage: '/assets/img/logo.png',
      imgNaturalWidth: 200,
      imgNaturalHeight: 200,
      animateStart: 1594263170277,
    },
  ],
  lineName: 'curve',
  fromArrowType: '',
  toArrowType: 'triangleSolid',
  scale: 1,
  locked: 0,
  mqttOptions: {
    clientId: '38a4ffb1',
  },
};
